# Generated by Django 4.2.5 on 2023-10-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0014_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='no image', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
