# Generated by Django 4.2.5 on 2023-10-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0039_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
